name: Deploy
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Performing Repository Checkout
              uses: actions/checkout@v2

            - name: Performing Pnpm Install on Workspace
              uses: pnpm/action-setup@v2.1.0
              with:
                version: 6.0.2

            - name: Transpiling TypeScript
              run: npx tsc

            - name: Deleting old files on Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: "rm -rf /home/ubuntu/projects/ts-discord-soundroid/dist"

            - name: Uploading new files to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  target: "/home/ubuntu/projects/ts-discord-soundroid"
                  source: "dist/*,package.json,pnpm-lock.yaml"

            - name: Performing Yarn Install on Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: "cd /home/ubuntu/projects/ts-discord-soundroid && pnpm i"

            - name: Writing to .env file
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd /home/ubuntu/projects/ts-discord-soundroid
                      echo 'FIREBASE__SERVICE_ACCOUNT__PROJECT_ID=${{ secrets.FIREBASE__SERVICE_ACCOUNT__PROJECT_ID }}' > .env
                      echo 'FIREBASE__SERVICE_ACCOUNT__PRIVATE_KEY=${{ secrets.FIREBASE__SERVICE_ACCOUNT__PRIVATE_KEY }}' >> .env
                      echo 'FIREBASE__SERVICE_ACCOUNT__CLIENT_EMAIL=${{ secrets.FIREBASE__SERVICE_ACCOUNT__CLIENT_EMAIL }}' >> .env
                      echo 'FIREBASE__COLLECTION=${{ secrets.FIREBASE__COLLECTION }}' >> .env
                      echo 'FIREBASE__DATABASE_URL=${{ secrets.FIREBASE__DATABASE_URL }}' >> .env
                      echo '' >> .env
                      echo 'DISCORD__TOKEN=${{ secrets.DISCORD__TOKEN }}' >> .env
                      echo 'DISCORD__BOT_ID=${{ secrets.DISCORD__BOT_ID }}' >> .env
                      echo 'DISCORD__DEV_ID=${{ secrets.DISCORD__DEV_ID }}' >> .env
                      echo '' >> .env
                      echo 'SPOTIFY__CLIENT_ID=${{ secrets.SPOTIFY__CLIENT_ID }}' >> .env
                      echo 'SPOTIFY__CLIENT_SECRET=${{ secrets.SPOTIFY__CLIENT_SECRET }}' >> .env
                      echo 'SPOTIFY__REFRESH_TOKEN=${{ secrets.SPOTIFY__REFRESH_TOKEN }}' >> .env
                      echo '' >> .env
                      echo 'GENIUS__ACCESS_TOKEN=${{ secrets.GENIUS__ACCESS_TOKEN }}' >> .env

            - name: Restarting PM2 Process
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: "pm2 flush ts-discord-soundroid && pm2 restart ts-discord-soundroid --update-env"
