name: Deploy
on:
    push:
        branches:
            - "main"
        paths-ignore:
            - "README.md"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Performing Repository Checkout
              uses: actions/checkout@v2

            - name: Deploying to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: "ts-discord-soundroid"
                  heroku_email: "zectan.projects.0@gmail.com"
